from utils.base_crawl import ImageCrawlBase


crawler = ImageCrawlBase()

if __name__ == "__main__":
    crawler.craw([
        {"query_str": "Sunset landscape", "limits": 10},
        {"query_str": "Cat portraits", "limits": 10},
        {"query_str": "Abstract art", "limits": 10},
        {"query_str": "Vintage cars", "limits": 10},
        {"query_str": "Beach vacation", "limits": 10},
        {"query_str": "City skyline", "limits": 10},
        {"query_str": "Cute puppies", "limits": 10},
        {"query_str": "Mountain hiking", "limits": 10},
        {"query_str": "Wedding decorations", "limits": 10},
        {"query_str": "Coffee cup", "limits": 10},
        {"query_str": "Technology gadgets", "limits": 10},
        {"query_str": "Autumn leaves", "limits": 10},
        {"query_str": "Famous landmarks", "limits": 10},
        {"query_str": "Starry night sky", "limits": 10}, 
        {"query_str": "Macro photography", "limits": 10},
        {"query_str": "Tropical paradise", "limits": 10},
        {"query_str": "Wildlife photography", "limits": 10},
        {"query_str": "Abstract patterns", "limits": 10},
        {"query_str": "Fitness motivation", "limits": 10},
        {"query_str": "Delicious desserts", "limits": 10},
        {"query_str": "Space exploration", "limits": 10},
        {"query_str": "Abstract architecture", "limits": 10},
        {"query_str": "Classic movie posters", "limits": 10}, 
        {"query_str": "Exotic fruits", "limits": 10},
        {"query_str": "Underwater world", "limits": 10},
        {"query_str": "Street art", "limits": 10},
        {"query_str": "Luxury watches", "limits": 10},
        {"query_str": "Musical instruments", "limits": 10},
        {"query_str": "National parks", "limits": 10},
        {"query_str": "Colorful balloons", "limits": 10},
        {"query_str": "Vintage bicycles", "limits": 10},
        {"query_str": "Futuristic cityscapes", "limits": 10},
        {"query_str": "Yoga poses", "limits": 10},
        {"query_str": "Retro fashion", "limits": 10},
        {"query_str": "Cultural festivals", "limits": 10},
        {"query_str": "Urban exploration", "limits": 10},
        {"query_str": "Watercolor paintings", "limits": 10},
        {"query_str": "Graffiti art", "limits": 10},
        {"query_str": "Concept cars", "limits": 10},
        {"query_str": "Home office setups", "limits": 10}, 
        {"query_str": "Fantasy landscapes", "limits": 10},
        {"query_str": "Sailing adventures", "limits": 10},
        {"query_str": "Time-lapse photography", "limits": 10}, 
        {"query_str": "Rainforest flora", "limits": 10},
        {"query_str": "Vintage airplanes", "limits": 10},
        {"query_str": "Minimalist architecture", "limits": 10},
        {"query_str": "Abstract digital  art", "limits": 10},
        {"query_str": "Classic book covers", "limits": 10}, 
        {"query_str": "Snowy landscapes", "limits": 10},
        {"query_str": "Wildlife conservation", "limits": 10},
        {"query_str": "X-ray images", "limits": 10},
        {"query_str": "Magnetic Resonance Imaging (MRI) scans", "limits": 10},
        {"query_str": "Electronic Health Records (EHR)", "limits": 10},
        {"query_str": "Medical charts and graphs", "limits": 10},
        {"query_str": "Histopathology slides", "limits": 10},
        {"query_str": "Ultrasound images", "limits": 10},
        {"query_str": "Medical illustrations", "limits": 10},
        {"query_str": "Anatomical diagrams", "limits": 10},
        {"query_str": "Microscopic medical images", "limits": 10},
        {"query_str": "Medical document templates", "limits": 10}
    
    ], root_folder=r"C:\Users\hoang\OneDrive\Desktop\nghich_prj\crawl_data_bot\downloads")